#!/bin/bash


bam="$1"
[[ -z "$1" ]] && { echo "Parameter 1 is empty" 1>&2; exit 1; }
peaks="$2"
[[ -z "$2" ]] && { echo "Parameter 2 is empty" 1>&2; exit 1; }
genome="$3"
[[ -z "$3" ]] && { echo "Parameter 3 is empty" 1>&2; exit 1; }
output_dir="$4"
[[ -z "$4" ]] && { echo "Parameter 4 is empty" 1>&2; exit 1; }
gatk_dir="$6"
[[ -z "$6" ]] && { echo "Parameter 6 is empty" 1>&2; exit 1; }


gatk --java-options "-Xmx4g" SelectVariants \
  -L "$peaks" \
  -R "$genome" \
  -V "$gatk_dir/gatk.vcf.gz" \
  --select-type INDEL --select-type NO_VARIATION \
  --select-type-to-exclude SNP --select-type-to-exclude MIXED \
  --select-type-to-exclude SYMBOLIC --select-type-to-exclude MNP \
  -O "$output_dir/gatk-indel.vcf"
