#!/bin/bash


bam="$1"
[[ -z "$1" ]] && { echo "Parameter 1 is empty" 1>&2; exit 1; }
peaks="$2"
[[ -z "$2" ]] && { echo "Parameter 2 is empty" 1>&2; exit 1; }
genome="$3"
[[ -z "$3" ]] && { echo "Parameter 3 is empty" 1>&2; exit 1; }
output_dir="$4"
[[ -z "$4" ]] && { echo "Parameter 4 is empty" 1>&2; exit 1; }
illumina_dir="$6"
[[ -z "$6" ]] && { echo "Parameter 6 is empty" 1>&2; exit 1; }


ln -sf "$(realpath --relative-to "$output_dir" "$illumina_dir"/results/variants/diploidSV.vcf)" "$output_dir/illumina-manta.vcf"
