#!/bin/bash


bam="$1"
[[ -z "$1" ]] && { echo "Parameter 1 is empty" 1>&2; exit 1; }
peaks="$2"
[[ -z "$2" ]] && { echo "Parameter 2 is empty" 1>&2; exit 1; }
genome="$3"
[[ -z "$3" ]] && { echo "Parameter 3 is empty" 1>&2; exit 1; }
output_dir="$4"
[[ -z "$4" ]] && { echo "Parameter 4 is empty" 1>&2; exit 1; }
varscan_dir="$7"
[[ -z "$7" ]] && { echo "Parameter 7 is empty" 1>&2; exit 1; }


gatk --java-options "-Xmx4g" SelectVariants \
  -L "$peaks" \
  -R "$genome" \
  -V "$varscan_dir/varscan.vcf.gz" \
  --select-type SNP --select-type NO_VARIATION \
  --select-type-to-exclude INDEL --select-type-to-exclude MIXED \
  --select-type-to-exclude SYMBOLIC --select-type-to-exclude MNP \
  -O "$output_dir/varscan-snp.vcf"
